In [4]:
import pandas as pd

In [5]:
obj=pd.Series(data=[4,1,3,-8])

In [6]:
print(obj)

0    4
1    1
2    3
3   -8
dtype: int64


In [7]:
obj.values

array([ 4,  1,  3, -8])

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2= pd.Series([4,1,3,-8],index=['d','b','a','c'])
obj2

d    4
b    1
a    3
c   -8
dtype: int64

In [10]:
obj2.values

array([ 4,  1,  3, -8])

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

3

In [13]:
obj2[obj2>0]

d    4
b    1
a    3
dtype: int64

In [14]:
obj2[['b','c']]

b    1
c   -8
dtype: int64

In [15]:
obj2>0

d     True
b     True
a     True
c    False
dtype: bool

In [16]:
obj2*4

d    16
b     4
a    12
c   -32
dtype: int64

In [17]:
obj2['d':'c']

d    4
b    1
a    3
c   -8
dtype: int64

In [19]:
obj2.index=['a','b','c','d']
obj2

a    4
b    1
c    3
d   -8
dtype: int64

In [20]:
obj2['c']=-12
obj2

a     4
b     1
c   -12
d    -8
dtype: int64

In [23]:
obj2[['a','d']]=[2,3]
obj2

a     2
b     1
c   -12
d     3
dtype: int64

In [26]:
obj2[['a','b','d']]=10,20,30 #done
obj2

a    10
b    20
c   -12
d    30
dtype: int64

In [25]:
obj2['a','d']=40,50
obj2

a    40
b    20
c   -12
d    50
dtype: int64

In [27]:
obj2[1]

20

In [28]:
import numpy as np
np.exp(obj2)

a    2.202647e+04
b    4.851652e+08
c    6.144212e-06
d    1.068647e+13
dtype: float64

In [ ]:
dict={'yash':100,'sam':200}

In [ ]:
s=pd.Series(dict)

In [ ]:
print(s)

yash    100
sam     200
dtype: int64


In [ ]:
s

yash    100
sam     200
dtype: int64

In [ ]:
i=['yash','harsh','sam']

In [ ]:
val=['100','0','200']

In [ ]:
s3=pd.Series(dict,i)

In [ ]:
s3

yash     100.0
harsh      NaN
sam      200.0
dtype: float64

In [ ]:
s2=pd.Series(val,index=i)

In [ ]:
s2

yash     100
harsh      0
sam      200
dtype: object

In [ ]:
s3['harsh']=1

In [ ]:
s3

yash     100.0
harsh      1.0
sam      200.0
dtype: float64

In [ ]:
s3['yash','sam']=[4,5]

In [ ]:
s3

yash     4.0
harsh    1.0
sam      5.0
dtype: float64

In [ ]:
s3[s3==5]

sam    5.0
dtype: float64

Multiply all the elements with 2

In [ ]:
obj2

d    4
b    1
a    3
c   -8
dtype: int64

In [ ]:
obj2*2

d     8
b     2
a     6
c   -16
dtype: int64

In [ ]:
obj2[obj2>=3]

d    4
a    3
dtype: int64

In [ ]:
obj2%2

d    0
b    1
a    1
c    0
dtype: int64

In [29]:
dict1={"Ohio":17000,"Oregon":18000,"Texas":19000,"California":20000}

In [30]:
s_dict1=pd.Series(dict1)

In [31]:
s_dict1

Ohio          17000
Oregon        18000
Texas         19000
California    20000
dtype: int64

In [32]:
s_dict1.index

Index(['Ohio', 'Oregon', 'Texas', 'California'], dtype='object')

In [33]:
s_dict1.values

array([17000, 18000, 19000, 20000])

In [34]:
s_dict1.index=["Atlanta","California","Texas","Oregon"]

In [35]:
s_dict1

Atlanta       17000
California    18000
Texas         19000
Oregon        20000
dtype: int64

In [36]:
n=pd.Series(1)

In [37]:
n

0    1
dtype: int64

In [38]:
type(n)

pandas.core.series.Series

In [40]:
type(dict1)

dict

In [41]:
type(dict1['Texas'])

int

In [42]:
s_dict1.name='population'

In [44]:
s_dict1

Atlanta       17000
California    18000
Texas         19000
Oregon        20000
Name: population, dtype: int64

In [45]:
s_dict1.index.name='State'

In [46]:
s_dict1

State
Atlanta       17000
California    18000
Texas         19000
Oregon        20000
Name: population, dtype: int64

In [48]:
s2=pd.Series(12,index=[4,6,8])

In [49]:
print(s2)

4    12
6    12
8    12
dtype: int64


In [55]:
p=pd.Series(['a','e','i','o','u'],index=['a','e','i','o','u'])

In [56]:
p

a    a
e    e
i    i
o    o
u    u
dtype: object

In [57]:
p.name="Vowels"

In [58]:
p.index.name="Vowels"

In [59]:
p

Vowels
a    a
e    e
i    i
o    o
u    u
Name: Vowels, dtype: object